name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show env
        run: |
          python -V
          pip -V
          which python
          uname -a

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install (dev)
        run: pip install -e ".[dev]" hypothesis pytest-cov pytest-benchmark

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Mypy
        run: mypy src/similitude

      - name: Run tests (with coverage xml)
        run: pytest -vv --maxfail=1 --cov=src/similitude --cov-report=xml --cov-report=term-missing

      # Uncomment these two steps if you enabled Codecov and added the badge:
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     file: ./coverage.xml
      #     flags: unittests
      #     fail_ci_if_error: true

      - name: Upload raw coverage file (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./coverage.xml
